coin/billing/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url
from django.views.generic import DetailView
from coin.billing import views

urlpatterns = patterns(
    '',
    url(r'^invoice/(?P<id>.+)/pdf$', views.invoice_pdf, name="invoice_pdf"),
    url(r'^invoice/(?P<id>.+)$', views.invoice, name="invoice"),
    # url(r'^invoice/(?P<id>.+)/validate$', views.invoice_validate, name="invoice_validate"),
)

coin/members/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url
from coin.members import forms
from coin.members import views
from django.views.generic.base import TemplateView
from . import registration_views as views_r
from coin import settings

from registration.signals import user_activated
from django.contrib.auth import login

def login_on_activation(sender, user, request, **kwargs):
    """Logs in the user after activation"""
    user.backend = 'django.contrib.auth.backends.ModelBackend'
    login(request, user)

# Registers the function with the django-registration user_activated signal
user_activated.connect(login_on_activation)

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
    url(r'^login/$', 'django.contrib.auth.views.login',
        {'template_name': 'members/registration/login.html',
         'extra_context': {'settings': settings} },
        name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login',
        name='logout'),

    url(r'^password_change/$', 'django.contrib.auth.views.password_change',
        {'post_change_redirect': 'members:password_change_done',
         'template_name': 'members/registration/password_change_form.html'},
        name='password_change'),
    url(r'^password_change_done/$', 'django.contrib.auth.views.password_change_done',
        {'template_name': 'members/registration/password_change_done.html'},
        name='password_change_done'),

    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset',
        {'post_reset_redirect': 'members:password_reset_done',
         'template_name': 'members/registration/password_reset_form.html',
         'email_template_name': 'members/registration/password_reset_email.html',
         'subject_template_name': 'members/registration/password_reset_subject.txt'},
        name='password_reset'),
    url(r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done',
        {'template_name': 'members/registration/password_reset_done.html',
         'current_app': 'members'},
        name='password_reset_done'),
    url(r'^password_reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm',
        {'post_reset_redirect': 'members:password_reset_complete',
         'template_name': 'members/registration/password_reset_confirm.html'},
        name='password_reset_confirm'),
    url(r'^password_reset/complete/$', 'django.contrib.auth.views.password_reset_complete',
        {'template_name': 'members/registration/password_reset_complete.html'},
        name='password_reset_complete'),


    url(r'^activate/complete/$', views.activation_completed,
        name='registration_activation_complete'),
    # The activation key can make use of any character from the
    # URL-safe base64 alphabet, plus the colon as a separator.
    url(r'^activate/(?P<activation_key>[-:\w]+)/$',
        views_r.MemberActivationView.as_view(),
        name='registration_activate'),
    url(r'^register/$',
        views_r.MemberRegistrationView.as_view(
            form_class=forms.MemberRegistrationForm,
            template_name='members/registration/registration_form.html'
        ),
        name='registration_register'),
    url(r'^register/complete/$',
        TemplateView.as_view(
            template_name='members/registration/registration_complete.html'
        ),
        name='registration_complete'),
    url(r'^register/closed/$',
        TemplateView.as_view(
            template_name='members/registration/registration_closed.html'
        ),
        name='registration_disallowed'),
    #url(r'', include('registration.auth_urls')),




    url(r'^detail/$', views.detail,
        name='detail'),

    url(r'^subscriptions/', views.subscriptions, name='subscriptions'),
    # url(r'^subscription/(?P<id>\d+)', views.subscriptions, name = 'subscription'),

    url(r'^invoices/', views.invoices, name='invoices'),
    url(r'^contact/', views.contact, name='contact'),
)

coin/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.apps import apps
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from coin import views
import coin.apps

import autocomplete_light
autocomplete_light.autodiscover()

from django.contrib import admin
admin.autodiscover()

from coin.isp_database.views import isp_json


def apps_urlpatterns():
    """ Yields url lists ready to be appended to urlpatterns list
    """
    for app_config in apps.get_app_configs():
        if isinstance(app_config, coin.apps.AppURLs):
            for prefix, pats in app_config.exported_urlpatterns:
                yield url(
                    r'^{}/'.format(prefix),
                    include(pats, namespace=prefix))

urlpatterns = patterns(
    '',
    url(r'^$', 'coin.members.views.index', name='home'),

    url(r'^isp.json$', isp_json),
    url(r'^members/', include('coin.members.urls', namespace='members')),
    url(r'^billing/', include('coin.billing.urls', namespace='billing')),
    url(r'^subscription/', include('coin.offers.urls', namespace='subscription')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^hijack/', include('hijack.urls', namespace='hijack')),

    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^feed/(?P<feed_name>.+)', views.feed, name='feed'),

    url(r'^autocomplete/', include('autocomplete_light.urls')),

)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Pluggable apps URLs
urlpatterns += list(apps_urlpatterns())


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

vpn/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from .views import VPNView, VPNGeneratePasswordView, get_graph

urlpatterns = patterns(
    '',
    # This is part of the generic configuration interface (the "name" is
    # the same as the "backend_name" of the model).
    url(r'^(?P<pk>\d+)$', VPNView.as_view(template_name="vpn/vpn.html"), name="details"),
    url(r'^password/(?P<pk>\d+)$', VPNGeneratePasswordView.as_view(template_name="vpn/fragments/password.html"), name="generate_password"),
    url(r'^graph/(?P<vpn_id>[0-9]+)/(?P<period>[a-z]+)$', get_graph, name="get_graph"),
    url(r'^graph/(?P<vpn_id>[0-9]+)$', get_graph, name="get_graph"),
)

coin/members/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from django.contrib.auth.forms import PasswordResetForm, ReadOnlyPasswordHashField
from django.forms.utils import ErrorList
from django.forms.forms import BoundField

from coin.members.models import Member

from registration.forms import RegistrationForm


class MemberRegistrationForm(RegistrationForm):
    # Protect against robot
    trap = forms.CharField(required=False, label='Trap',
            widget=forms.TextInput(attrs={'style' : 'display:none'}),
        help_text="Si vous êtes humain ignorez ce champ")

    def __init__(self, *args, **kwargs):
        super(MemberRegistrationForm, self).__init__(*args, **kwargs)

        for fieldname in ['email', 'organization_name', 'password2']:
            self.fields[fieldname].help_text = None

    def is_valid(self):
         valid = super(MemberRegistrationForm,self).is_valid()
         avoid_trap = not self.data['trap']
         if valid and avoid_trap:
             return True
         else:
             return False

    def as_p(self):
        """"
        We rewrite the as_p method to apply a style on the <p> tag related to
        trap field. Indeed, it seeems there is no cleaner way to do it.
        """
        def css_classes(self, extra_classes=None):
            return 'captcha'

        func_type = type(BoundField.css_classes)
        self['trap'].css_classes = func_type(css_classes, self, BoundField)
        return super(MemberRegistrationForm, self).as_p()

    class Meta:
        model = Member
        fields = ['type', 'first_name', 'last_name',
                  'organization_name', 'email', 'username', 'trap']

class MemberCreationForm(forms.ModelForm):

    """
    This form was inspired from django.contrib.auth.forms.UserCreationForm
    and adapted to coin specificities
    """
    username = forms.RegexField(required=False,
                                label="Nom d'utilisateur", max_length=30, regex=r"^[\w.@+-]+$",
                                help_text="Laisser vide pour le générer automatiquement à partir du "
                                "nom d'usage, nom et prénom, ou nom de l'organisme")
    password = forms.CharField(
        required=False, label='Mot de passe', widget=forms.PasswordInput,
        help_text="Laisser vide et envoyer un mail de bienvenue pour que "
        "l'utilisateur choisisse son mot de passe lui-même")

    class Meta:
        model = Member
        fields = '__all__'

    def save(self, commit=True):
        """
        Save member, then set his password
        """
        member = super(MemberCreationForm, self).save(commit=False)
        member.set_password(self.cleaned_data["password"])
        if commit:
            member.member()
        return member


class AbstractMemberChangeForm(forms.ModelForm):
    """
    This form was inspired from django.contrib.auth.forms.UserChangeForm
    and adapted to coin specificities
    """

    class Meta:
        model = Member
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(AbstractMemberChangeForm, self).__init__(*args, **kwargs)
        f = self.fields.get('user_permissions', None)
        if f is not None:
            f.queryset = f.queryset.select_related('content_type')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

    def clean_username(self):
        # idem clean_password
        return self.initial["username"]


class AdminMemberChangeForm(AbstractMemberChangeForm):
    password = ReadOnlyPasswordHashField()


class SpanError(ErrorList):
    def __unicode__(self):
        return self.as_spans()
    def __str__(self):
        return self.as_spans()
    def as_spans(self):
        if not self: return ''
        return ''.join(['<span class="error">%s</span>' % e for e in self])

class PersonMemberChangeForm(AbstractMemberChangeForm):
    """
    Form use to allow natural person to change their info
    """
    class Meta:
        model = Member
        fields = ['first_name', 'last_name', 'email', 'nickname',
                  'home_phone_number', 'mobile_phone_number',
                  'address', 'postal_code', 'city', 'country']

    def __init__(self, *args, **kwargs):
        super(PersonMemberChangeForm, self).__init__(*args, **kwargs)
        self.error_class = SpanError
        for fieldname in self.fields:
            self.fields[fieldname].help_text = None


class OrganizationMemberChangeForm(AbstractMemberChangeForm):
    """
    Form use to allow organization to change their info
    """
    class Meta:
        model = Member
        fields = ['organization_name', 'email', 'nickname',
                  'home_phone_number', 'mobile_phone_number',
                  'address', 'postal_code', 'city', 'country']

    def __init__(self, *args, **kwargs):
        super(OrganizationMemberChangeForm, self).__init__(*args, **kwargs)
        self.error_class = SpanError
        for fieldname in self.fields:
            self.fields[fieldname].help_text = None

class MemberPasswordResetForm(PasswordResetForm):
    pass

coin/members/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.template import RequestContext
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.conf import settings
from forms import PersonMemberChangeForm, OrganizationMemberChangeForm

@login_required
def index(request):
    has_isp_feed = 'isp' in [k for k, _, _ in settings.FEEDS]
    return render(request, 'members/index.html',
                  {'has_isp_feed': has_isp_feed})


@login_required
def detail(request):

    membership_info_url = settings.MEMBER_MEMBERSHIP_INFO_URL
    context={
        'membership_info_url': membership_info_url,
    }

    if settings.MEMBER_CAN_EDIT_PROFILE:
        if request.user.type == "natural_person":
            form_cls = PersonMemberChangeForm
        else:
            form_cls = OrganizationMemberChangeForm

        if request.method == "POST":
            form = form_cls(data = request.POST, instance = request.user)
            if form.is_valid():
                form.save()
        else:
            form = form_cls(instance = request.user)

        context['form'] = form

    return render(request, 'members/detail.html', context)


@login_required
def subscriptions(request):
    subscriptions = request.user.get_active_subscriptions()
    old_subscriptions = request.user.get_inactive_subscriptions()

    return render(request, 'members/subscriptions.html',
                  {'subscriptions': subscriptions,
                   'old_subscriptions': old_subscriptions})


@login_required
def invoices(request):
    balance  = request.user.balance
    invoices = request.user.invoices.filter(validated=True).order_by('-date')
    payments = request.user.payments.filter().order_by('-date')

    return render(request, 'members/invoices.html',
                              {'balance' : balance,
                               'handle_balance' : settings.HANDLE_BALANCE,
                               'invoices': invoices,
                               'payments': payments})


@login_required
def contact(request):
    return render(request, 'members/contact.html')


@login_required
def activation_completed(request):
    label_template = settings.MEMBERSHIP_REFERENCE.format(user=request.user)
    context = {
        'bank_transfer_label': label_template,
        'dues': settings.DEFAULT_MEMBERSHIP_FEE
    }

    return render(request, 'members/registration/activation_complete.html',
                  context)

coin/members/templates/members/contact.html
{% extends "base.html" %}
{% block title %}Contact / Support - {{ block.super }}{% endblock %}

{% block content %}
<div class="row">
    <div class="large-12 columns">
        <h2>Contact / Support</h2>
        <div class="panel">
            <h3>Courriel</h3>
            <p>
                <a href="mailto:{{ branding.email }}">{{ branding.email }}</a> (questions générales)<br />
                {% if branding.administrative_email %}
                <a href="mailto:{{ branding.administrative_email }}">{{ branding.administrative_email }}</a> (questions administratives)<br />
                {% endif %}
                {% if branding.support_email %}
                <a href="mailto:{{ branding.support_email }}">{{ branding.support_email }}</a> (support technique)
                {% endif %}
            </p>
        </div>
        {% if branding.lists_url %}
        <div class="panel">
            <h3>Listes de discussion</h3>
            <p>Gérer ses abonnements aux listes de discussion et diffusion : <a href="{{ branding.lists_url }}">{{ branding.lists_url }}</a></p>
        </div>
        {% endif %}
        {% if branding.main_chat_verbose %}
        <div class="panel">
            <h3>IRC</h3>
            <p><a href="{{ branding.chatroom_set.first.url }}">{{ branding.main_chat_verbose }}</a></p>
        </div>
        {% endif %}
        {% if branding.phone_number %}
        <div class="panel">
            <h3>Téléphone</h3>
            <p><a href="tel:{{ branding.phone_number|cut:' ' }}">{{ branding.phone_number }}</a></p>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

coin/members/templates/members/detail.html
{% extends "base.html" %}

{% block title %}Mes informations - {{ block.super }}{% endblock %}

{% block content %}
<div class="row">
    <div class="large-12 columns">
        <h2>Mes informations personnelles</h2>
    </div>
</div>
<div class="row">
    <div class="large-6 columns">
        <div class="panel">
            <h3>Mes coordonnées</h3>
            <table id="personnal-info" class="full-width no-border no-background">
            {% if user.type == 'natural_person' %}
                {% if user.first_name %}
                <tr class="first-name">
                    <td>Prénom</td>
                    <td>{{user.first_name}}</td>
                </tr>
                {% endif %}
                {% if user.last_name %}
                <tr class="last-name">
                    <td>Nom</td>
                    <td>{{user.last_name}}</td>
                </tr>
                {% endif %}
                {% if user.nickname %}
                <tr class="nickname">
                    <td>Pseudo</td>
                    <td>{{ user.nickname }}</td>
                </tr>
                {% endif %}
            {% else %}
                <tr class="organization-name">
                    <td>Nom de la structure</td>
                    <td>{{ user.organization_name }}</td>
                </tr>
            {% endif %}

            {% if user.address %}
                <tr class="address">
                    <td>Adresse</td>
                    <td>{{user.address}}<br />{{user.postal_code}} {{user.city}}</td>
                </tr>
            {% endif %}

            {% if user.email %}
                <tr class="email">
                    <td>Email</td>
                    <td>{{user.email}}</td>
                </tr>
            {% endif %}

            {% if user.home_phone_number %}
                <tr class="phone-number">
                    <td>Téléphone fixe</td>
                    <td>{{user.home_phone_number}}</td>
                </tr>
            {% endif %}

            {% if user.mobile_phone_number %}
                <tr class="mobile-number">
                    <td>Téléphone mobile</td>
                    <td>{{user.mobile_phone_number}}</td>
                </tr>
            {% endif %}
            </table>
        </div>
    </div>

    <div class="large-6 columns">
        <div class="panel">
            <h3>Membre de {{ branding.shortname|capfirst }}</h3>
            <p>Ma cotisation est :
                {% if user.is_paid_up %}
                    <span class="label success">à jour !</span>
                {% else %}
                    <span class="label alert">non à jour !</span>
                {% endif %}
            </p>
            <p>
                {% if  user.end_date_of_membership %}
                Date de fin de cotisation : {{ user.end_date_of_membership }}
                {% else %}
                Je n'ai encore jamais cotisé.
                {% endif %}
            </p>

            {% if membership_info_url %}
            <a href="{{ membership_info_url }}" class="button small radius expand">
                <i class="fa fa-heart"></i> Renouveler ma cotisation
            </a>
            {% endif %}
        </div>

    </div>

</div>
<div class="row">
    <div class="large-12 columns">
        {% if form %}
            <form method="post" action="">
                {% csrf_token %}
                <fieldset class="module aligned wide">
                {{ form.as_p }}
                </fieldset>
                <input type="submit" class="button radius" value="Modifier"/>
            </form>
        {% else %}
            <p>
                Pour modifier vos informations personnelles et vos coordonnées, veuillez en faire la demande
                {% if branding.administrative_email %}
                par email à <a href="mailto:{{ branding.administrative_email }}">{{ branding.administrative_email }}</a>.
                {% else %}
                à l'association.
                {% endif%}
            </p>
        {% endif %}
    </div>
</div>

{% endblock %}

coin/members/templates/members/index.html
{% extends "base.html" %}

{% block title %}Tableau de bord - {{ block.super }}{% endblock %}

{% block content %}
<div class="row">
    <div class="large-12 columns">
        <h2>Tableau de bord</h2>
    </div>
</div>

<div class="row">
    <div class="large-6 columns">
        <div class="panel">
            <h3>Alertes</h3>
            <p>Ici les news de santé des serveurs, etc.</p>
        </div>
    </div>
    <div class="large-6 columns">
        <div class="panel">
            <h3>Stats</h3>
            <p>Use MOAR bandwidth !</p>
        </div>
    </div>
    {% if has_isp_feed %}
    <div class="large-6 columns">
        <div class="panel">
            <h3>News {{ branding.shortname|capfirst }}</h3>
            <div id="feed_isp">
            <p>
                <i class="fa fa-spinner fa-spin"></i>
                Chargement en cours
            </p>
            </div>
        </div>
    </div>
    {% endif %}
    <div class="large-6 columns">
        <div class="panel">
            <h3>News de la FFDN</h3>
            <div id="feed_ffdn">
            <p>
                <i class="fa fa-spinner fa-spin"></i>
                Chargement en cours
            </p>
            </div>
        </div>
    </div>
</div>

{% endblock %}


{% block extra_js %}
    {{ block.super }}
    <script>
    $(function() {
        {% if has_isp_feed %}
        $.ajax({
            url: "{% url 'feed' feed_name='isp' %}",
        }).done(function(html) {
            $('#feed_isp').html(html);
        }).fail(function() {
            $('#feed_isp').html('Erreur lors du chargement du flux');
        });
        {% endif %}
        $.ajax({
            url: "{% url 'feed' feed_name='ffdn' %}",
        }).done(function(html) {
            $('#feed_ffdn').html(html);
        }).fail(function() {
            $('#feed_ffdn').html('Erreur lors du chargement du flux');
        });
    });
    </script>
{% endblock extra_js %}

coin/members/templates/members/invoices.html
{% extends "base.html" %}

{% block title %}Factures & paiements - {{ block.super }}{% endblock %}

{% block content %}

{% if handle_balance %}
	<h2>Solde : {{ balance|floatformat }} €</h2>
{% endif %}

<h2>Mes factures</h2>

<table id="member_invoices" class="full-width">
    <thead>
        <tr>
            <th>Numéro</th>
            <th>Date</th>
            <th>Montant</th>
            <th>Reste à payer</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for invoice in invoices %}
        <tr>
            <td><a href="{% url 'billing:invoice' id=invoice.number %}">{{ invoice.number }}</a></td>
            <td>{{ invoice.date }}</td>
            <td>{{ invoice.amount }}</td>
            <td{% if invoice.amount_remaining_to_pay > 0 %} class="unpaid"{% endif %}>{{ invoice.amount_remaining_to_pay }}</td>
            <td>{% if invoice.validated %}<a href="{% url 'billing:invoice_pdf' id=invoice.number %}"><i class="fa fa-file-pdf-o"></i> PDF</a>{% endif %}</td>
        </tr>
        {% empty %}
        <tr class="placeholder"><td colspan="6">Aucune facture.</td></tr>
        {% endfor %}
    </tbody>
</table>


<h2>Mes paiements</h2>

<table id="member_payments" class="full-width">
    <thead>
        <tr>
            <th>Date</th>
            <th>Montant</th>
            <th>Alloué</th>
        </tr>
    </thead>
    <tbody>
        {% for payment in payments %}
        <tr>
            <td>{{ payment.date }}</td>
            <td>{{ payment.amount }}</td>
            <td>{{ payment.amount_already_allocated }}</td>
        </tr>
        {% empty %}
        <tr class="placeholder"><td colspan="6">Aucun paiement.</td></tr>
        {% endfor %}
    </tbody>
</table>


<h2>Coordonnées bancaires</h2>
<div id="payment-howto" class="panel">
    {% include "billing/payment_howto.html" %}
</div>
{% endblock %}

coin/members/templates/members/subscriptions.html
{% extends "base.html" %}

{% block title %}Mes abonnements - {{ block.super }}{% endblock %}

{% block content %}
<h2>Mes abonnements</h2>

<table id="member_subscriptions" class="full-width">
    <thead>
        <tr>
            <th width="60">Type</th>
            <th>Offre</th>
            <th>Date de souscription</th>
            <th>Date de résiliation</th>
            <th>Commentaire</th>
            <th>Configuration</th>
        </tr>
    </thead>
    <tbody>
        {% for subscription in subscriptions %}
        <tr>
            <td>{{ subscription.offer.get_configuration_type_display }}</td>
            <td>{{ subscription.offer.name }}</td>
            <td>{{ subscription.subscription_date }}</td>
            <td>{{ subscription.resign_date|default_if_none:"" }}</td>
            <td>{{ subscription.configuration.comment }}</td>
            <td>{% if subscription.configuration and subscription.configuration.url_namespace %}<a class="cfglink" href="{% url subscription.configuration.get_url_namespace|add:":details" pk=subscription.configuration.pk %}"><i class="fa fa-cog"></i> Configuration</a>{% endif %}</td>
            
        </tr>
        {% endfor %}
        {% for subscription in old_subscriptions %}
        <tr class="inactive">
            <td>{{ subscription.offer.get_configuration_type_display }}</td>
            <td>{{ subscription.offer.name }}</td>
            <td>{{ subscription.subscription_date }}</td>
            <td>{{ subscription.resign_date|default_if_none:"" }}</td>
            <td>{{ subscription.configuration.comment }}</td>
            <td></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<!--
     <div class="panel">
         <h3>Stats générales ADSL</h3>
         <a class="button">Voir l'ADSL</a>
     </div>
     <div class="panel">
         <h3>Stats générales VPN</h3>
         <a class="button">Voir le VPN</a>
     </div>-->

{% endblock %}