coin/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.apps import apps
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from coin import views
import coin.apps

import autocomplete_light
autocomplete_light.autodiscover()

from django.contrib import admin
admin.autodiscover()

from coin.isp_database.views import isp_json


def apps_urlpatterns():
    """ Yields url lists ready to be appended to urlpatterns list
    """
    for app_config in apps.get_app_configs():
        if isinstance(app_config, coin.apps.AppURLs):
            for prefix, pats in app_config.exported_urlpatterns:
                yield url(
                    r'^{}/'.format(prefix),
                    include(pats, namespace=prefix))

urlpatterns = patterns(
    '',
    url(r'^$', 'coin.members.views.index', name='home'),

    url(r'^isp.json$', isp_json),
    url(r'^members/', include('coin.members.urls', namespace='members')),
    url(r'^billing/', include('coin.billing.urls', namespace='billing')),
    url(r'^subscription/', include('coin.offers.urls', namespace='subscription')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^hijack/', include('hijack.urls', namespace='hijack')),

    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^feed/(?P<feed_name>.+)', views.feed, name='feed'),

    url(r'^autocomplete/', include('autocomplete_light.urls')),

)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Pluggable apps URLs
urlpatterns += list(apps_urlpatterns())


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

vpn/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from .views import VPNView, VPNGeneratePasswordView, get_graph

urlpatterns = patterns(
    '',
    # This is part of the generic configuration interface (the "name" is
    # the same as the "backend_name" of the model).
    url(r'^(?P<pk>\d+)$', VPNView.as_view(template_name="vpn/vpn.html"), name="details"),
    url(r'^password/(?P<pk>\d+)$', VPNGeneratePasswordView.as_view(template_name="vpn/fragments/password.html"), name="generate_password"),
    url(r'^graph/(?P<vpn_id>[0-9]+)/(?P<period>[a-z]+)$', get_graph, name="get_graph"),
    url(r'^graph/(?P<vpn_id>[0-9]+)$', get_graph, name="get_graph"),
)

vps/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from .views import VPSView

urlpatterns = patterns(
    '',
    # This is part of the generic configuration interface (the "name" is
    # the same as the "backend_name" of the model).
    url(r'^(?P<pk>\d+)$', VPSView.as_view(template_name="vps/vps.html"), name="details"),
)

vps/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from polymorphic import PolymorphicModel
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from netfields import InetAddressField, NetManager

from coin.configuration.models import Configuration
# from coin.offers.backends import ValidateBackendType
from coin import validation


"""BIG FAT WARNING

Ce code requiert une sévère factorisation avec vpn/models.py et
housing/models.py

"""

FINGERPRINT_TYPES = (
    ('ED25519', 'ED25519'),
    ('RSA', 'RSA'),
    ('ECDSA', 'ECDSA')
)

PROTOCOLE_TYPES = (
    ('VNC', 'VNC'),
)


class VPSConfiguration(Configuration):
    url_namespace = "vps"
    activated = models.BooleanField(default=False, verbose_name='activé')
    ipv4_endpoint = InetAddressField(validators=[validation.validate_v4],
                                     verbose_name="IPv4", blank=True, null=True,
                                     help_text="Adresse IPv4 utilisée par "
                                     "défaut sur le VPS")
    ipv6_endpoint = InetAddressField(validators=[validation.validate_v6],
                                     verbose_name="IPv6", blank=True, null=True,
                                     help_text="Adresse IPv6 utilisée par "
                                     "défaut sur le VPS")
    objects = NetManager()

    def get_absolute_url(self):
        return reverse('vps:details', args=[str(self.pk)])

    # This method is part of the general configuration interface.
    def subnet_event(self):
        self.check_endpoints(delete=True)
        # We potentially changed the endpoints, so we need to save.  Also,
        # saving will update the subnets in the LDAP backend.
        self.full_clean()
        self.save()

    def get_subnets(self, version):
        subnets = self.ip_subnet.all()
        return [subnet for subnet in subnets if subnet.inet.version == version]

    def generate_endpoints(self, v4=True, v6=True):
        """Generate IP endpoints in one of the attributed IP subnets.  If there is
        no available subnet for a given address family, then no endpoint
        is generated for this address family.  If there already is an
        endpoint, do nothing.

        Returns True if an endpoint was generated.

        TODO: this should be factored for other technologies (DSL, etc)

        """
        subnets = self.ip_subnet.all()
        updated = False
        if v4 and self.ipv4_endpoint is None:
            subnets_v4 = [s for s in subnets if s.inet.version == 4]
            if len(subnets_v4) > 0:
                self.ipv4_endpoint = subnets_v4[0].inet.ip
                updated = True
        if v6 and self.ipv6_endpoint is None:
            subnets_v6 = [s for s in subnets if s.inet.version == 6]
            if len(subnets_v6) > 0:
                # With v6, we choose the second host of the subnet (cafe::1)
                gen = subnets_v6[0].inet.iter_hosts()
                gen.next()
                self.ipv6_endpoint = gen.next()
                updated = True
        return updated

    def check_endpoints(self, delete=False):
        """Check that the IP endpoints are included in one of the attributed IP
        subnets.

        If [delete] is True, then simply delete the faulty endpoints
        instead of raising an exception.
        """
        error = "L'IP {} n'est pas dans un réseau attribué."
        subnets = self.ip_subnet.all()
        is_faulty = lambda endpoint : endpoint and not any([endpoint in subnet.inet for subnet in subnets])
        if is_faulty(self.ipv4_endpoint):
            if delete:
                self.ipv4_endpoint = None
            else:
                raise ValidationError(error.format(self.ipv4_endpoint))
        if is_faulty(self.ipv6_endpoint):
            if delete:
                self.ipv6_endpoint = None
            else:
                raise ValidationError(error.format(self.ipv6_endpoint))

    def clean(self):
        # If saving for the first time and IP endpoints are not specified,
        # generate them automatically.
        if self.pk is None:
            self.generate_endpoints()
        self.check_endpoints()

    def __unicode__(self):
        return 'VPS ' + str(self.offersubscription.member.username) + ' ' + self.offersubscription.member.last_name

    class Meta:
        verbose_name = 'VPS'

class FingerPrint(PolymorphicModel):
    vps = models.ForeignKey(VPSConfiguration, verbose_name="vps")
    algo = models.CharField(max_length=256, verbose_name="algo",
                            choices=FINGERPRINT_TYPES)
    fingerprint = models.CharField(max_length=256, verbose_name="empreinte")
    length = models.IntegerField(verbose_name="longueur de la clé", null=True)

    class Meta:
        verbose_name = 'Empreinte'


class Console(models.Model):
    vps = models.OneToOneField(VPSConfiguration, verbose_name="vps")
    protocol = models.CharField(max_length=256, verbose_name="protocole",
                            choices=PROTOCOLE_TYPES)
    domain = models.CharField(max_length=256, verbose_name="nom de domaine",
                                blank=True, null=True)
    port = models.IntegerField(verbose_name="port", null=True)
    password_link = models.URLField(verbose_name="Mot de passe", blank=True,
                           null=True, help_text="Lien à usage unique (détruit après ouverture)")
    class Meta:
        verbose_name = 'Console'

vps/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404
from django.views.generic.edit import UpdateView
from django.conf import settings
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from coin.members.models import Member

from .models import VPSConfiguration


class VPSView(SuccessMessageMixin, UpdateView):
    model = VPSConfiguration
    fields = ['ipv4_endpoint', 'ipv6_endpoint', 'comment']
    success_message = "Configuration enregistrée avec succès !"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(VPSView, self).dispatch(*args, **kwargs)

    def get_form(self, form_class=None):
        if settings.MEMBER_CAN_EDIT_VPS_CONF:
            return super(VPSView, self).get_form(form_class)
        return None

    def get_object(self):
        if self.request.user.is_superuser:
            return get_object_or_404(VPSConfiguration, pk=self.kwargs.get("pk"))
        # For normal users, ensure the VPS belongs to them.
        return get_object_or_404(VPSConfiguration, pk=self.kwargs.get("pk"),
                                 offersubscription__member=self.request.user)

vps/templates/vps/vps.html
{% extends "base.html" %}

{% load subnets %}

{% block content %}
<div class="row">
    <h2>Configuration du VPS</h2>
    {% if form %}
        <form class="flatform" action="{{ object.get_absolute_url }}" method="post">{% csrf_token %}
        <p class="legend">Quand vous aurez terminé vos modifications, cliquez sur <input class="button" type="submit" value="Valider" /></p>
    {% endif %}
    {% for message in messages %}
        <div class="message eat-up{% if message.tags %} {{ message.tags }}{% endif %}">
            {{ message }}
        </div>
    {% endfor %}

    {% if form %}
        {% if form.non_field_errors or form.ipv4_endpoint.errors or form.ipv6_endpoint.errors %}
            <div class="alert-box alert nogap">
            {{ form.non_field_errors }}
            {{ form.ipv4_endpoint.errors }}
            {{ form.ipv6_endpoint.errors }}
            </div>
        {% endif %}
    {% endif %}
    <div class="large-12 columns">
        <div class="panel">
            <h3>Authentification</h3>
            <table class="full-width">
                {% if object.fingerprint_set.all %}
                <tr>
                    <td class="center"><span class="label">Empreinte(s)</span></td>
                    <td>{% for fingerprint in object.fingerprint_set.all %}
                        {{ fingerprint.length }} {{ fingerprint.fingerprint }} ({{ fingerprint.algo }}){% if not forloop.last %}<br />{% endif %}
                        {% endfor %}</td>
                </tr>
                {% endif %}
                {% if object.console %}
                <tr>
                    <td class="center"><span class="label">Console {{object.console.protocol }}</span></td>
                    <td>
                        {{ object.console.domain }}:{{ object.console.port }}<br />

                    <a href="{{object.console.password_link}}">Voir le mot de passe (lien supprimé après ouverture)</a>
                    </td>
                </tr>
                {% endif %}
                <tr class="flatfield">
                    {% if form %}
                        <td class="center">{{ form.comment.label_tag }}</td>
                        <td>{{ form.comment }}</td>
                    {% else %}
                    <td class="center"><span class="label">Commentaire</span></td>
                        <td>{{ object.comment }}</td>
                        
                    {% endif %}
                </tr>
                <tr>
                    <td class="center boolviewer" colspan="2">
                    {% if form %}
                        <input type="checkbox" disabled="disabled"{% if object.activated %} checked="checked"{% endif %} />
                    {% endif %}
                        <span>Ce VPS est {{ object.activated|yesno:"activé,désactivé" }}</span>
                    </td>
                </tr>
            </table>
        </div>
    </div>

    <div class="large-12 columns">
        <div class="panel">
            <h3>Adresses IP</h3>
            <table class="full-width">
                {% if form %}
                    <tr class="flatfield">
                        <td class="center">{{ form.ipv4_endpoint.label_tag }}</td>
                        <td{% if form.non_field_errors or form.ipv4_endpoint.errors %} class="errored"{% endif %}>{{ form.ipv4_endpoint }}</td>
                    </tr>
                    <tr class="flatfield">
                        <td class="center">{{ form.ipv6_endpoint.label_tag }}</td>
                        <td{% if form.non_field_errors or form.ipv6_endpoint.errors %} class="errored"{% endif %}>{{ form.ipv6_endpoint }}</td>
                    </tr>
                {% else %}
                    <tr class="flatfield">
                        <td class="center"><span class="label">IPv4</span></td>
                        <td>{{ object.ipv4_endpoint }}</td>
                    </tr>
                    <tr class="flatfield">
                        <td class="center"><span class="label">IPv6</span></td>
                        <td>{{ object.ipv6_endpoint }}</td>
                    </tr>
                {% endif %}
                <tr>
                    <td class="center"><span class="label">Sous-réseaux</span></td>
                    <td>
                        {% for subnet in object.ip_subnet.all %}{{ subnet|prettify }}<br/>{% endfor %}
                    </td>
                </tr>
            </table>
        </div>
    </div>
    {% if form %}
    <p class="formcontrol"><input class="button" type="submit" value="Valider" /></p>
    </form>
    {% endif %}
</div>

{% endblock %}