coin/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.apps import apps
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from coin import views
import coin.apps

import autocomplete_light
autocomplete_light.autodiscover()

from django.contrib import admin
admin.autodiscover()

from coin.isp_database.views import isp_json


def apps_urlpatterns():
    """ Yields url lists ready to be appended to urlpatterns list
    """
    for app_config in apps.get_app_configs():
        if isinstance(app_config, coin.apps.AppURLs):
            for prefix, pats in app_config.exported_urlpatterns:
                yield url(
                    r'^{}/'.format(prefix),
                    include(pats, namespace=prefix))

urlpatterns = patterns(
    '',
    url(r'^$', 'coin.members.views.index', name='home'),

    url(r'^isp.json$', isp_json),
    url(r'^members/', include('coin.members.urls', namespace='members')),
    url(r'^billing/', include('coin.billing.urls', namespace='billing')),
    url(r'^subscription/', include('coin.offers.urls', namespace='subscription')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^hijack/', include('hijack.urls', namespace='hijack')),

    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^feed/(?P<feed_name>.+)', views.feed, name='feed'),

    url(r'^autocomplete/', include('autocomplete_light.urls')),

)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Pluggable apps URLs
urlpatterns += list(apps_urlpatterns())


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

vpn/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from .views import VPNView, VPNGeneratePasswordView, get_graph

urlpatterns = patterns(
    '',
    # This is part of the generic configuration interface (the "name" is
    # the same as the "backend_name" of the model).
    url(r'^(?P<pk>\d+)$', VPNView.as_view(template_name="vpn/vpn.html"), name="details"),
    url(r'^password/(?P<pk>\d+)$', VPNGeneratePasswordView.as_view(template_name="vpn/fragments/password.html"), name="generate_password"),
    url(r'^graph/(?P<vpn_id>[0-9]+)/(?P<period>[a-z]+)$', get_graph, name="get_graph"),
    url(r'^graph/(?P<vpn_id>[0-9]+)$', get_graph, name="get_graph"),
)

vpn/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.exceptions import ValidationError
from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from django.core.urlresolvers import reverse
from netfields import InetAddressField, NetManager
import ldapdb.models
from ldapdb.models.fields import CharField, ListField

from coin.mixins import CoinLdapSyncMixin
from coin.configuration.models import Configuration
# from coin.offers.backends import ValidateBackendType
from coin import utils
from coin import validation

"""BIG FAT WARNING

Ce code requiert une sévère factorisation avec housing/models.py et
vps/models.py

"""


class VPNConfiguration(CoinLdapSyncMixin, Configuration):
    url_namespace = "vpn"
    # backend_name = "openvpn_ldap"
    # administrative_subscription = models.OneToOneField(
    #     'offers.OfferSubscription',
    #     related_name=backend_name,
    #     validators=[ValidateBackendType(backend_name)])
    activated = models.BooleanField(default=False, verbose_name='activé')
    login = models.CharField(max_length=50, unique=True, blank=True,
                             verbose_name="identifiant",
                             help_text="Laisser vide pour une génération automatique")
    password = models.CharField(max_length=256, verbose_name="mot de passe",
                                blank=True, null=True)
    ipv4_endpoint = InetAddressField(validators=[validation.validate_v4],
                                     verbose_name="IPv4", blank=True, null=True,
                                     help_text="Adresse IPv4 utilisée par "
                                     "défaut sur le VPN")
    ipv6_endpoint = InetAddressField(validators=[validation.validate_v6],
                                     verbose_name="IPv6", blank=True, null=True,
                                     help_text="Adresse IPv6 utilisée par "
                                     "défaut sur le VPN")
    crypto_link = models.URLField(verbose_name="Matériel cryptographique", blank=True,
                           null=True, help_text="Lien à usage unique (détruit après ouverture)")
    objects = NetManager()

    METHOD_CRYPTO_LINK = 'crypto-link'
    METHOD_GEN_PASSWORD_AND_FORGET = 'gen-password-and-forget'

    SECRETS_TRANSMISSION_METHOD = settings.VPN_SECRETS_TRANSMISSION_METHOD

    if SECRETS_TRANSMISSION_METHOD not in (
            METHOD_CRYPTO_LINK, METHOD_GEN_PASSWORD_AND_FORGET):
        raise ImproperlyConfigured(
            'Invalid value for VPN_SECRETS_TRANSMISSION_METHOD setting: {}'.format(
                SECRETS_TRANSMISSION_METHOD))

    def get_absolute_url(self):
        return reverse('vpn:details', args=[str(self.pk)])

    # This method is part of the general configuration interface.
    def subnet_event(self):
        self.check_endpoints(delete=True)
        # We potentially changed the endpoints, so we need to save.  Also,
        # saving will update the subnets in the LDAP backend.
        self.full_clean()
        self.save()

    def get_subnets(self, version):
        subnets = self.ip_subnet.all()
        return [subnet for subnet in subnets if subnet.inet.version == version]

    def sync_to_ldap(self, creation, *args, **kwargs):
        if creation:
            config = LdapVPNConfig()
        else:
            config = LdapVPNConfig.objects.get(pk=self.login)
        config.login = config.sn = self.login
        config.password = self.password
        config.active = 'yes' if self.activated else 'no'
        config.ipv4_endpoint = utils.str_or_none(self.ipv4_endpoint)
        config.ipv6_endpoint = utils.str_or_none(self.ipv6_endpoint)
        config.ranges_v4 = [str(s) for s in self.get_subnets(4)]
        config.ranges_v6 = [str(s) for s in self.get_subnets(6)]
        config.save()

    def delete_from_ldap(self):
        LdapVPNConfig.objects.get(pk=self.login).delete()

    def generate_endpoints(self, v4=True, v6=True):
        """Generate IP endpoints in one of the attributed IP subnets.  If there is
        no available subnet for a given address family, then no endpoint
        is generated for this address family.  If there already is an
        endpoint, do nothing.

        Returns True if an endpoint was generated.

        TODO: this should be factored for other technologies (DSL, etc)

        """
        subnets = self.ip_subnet.all()
        updated = False
        if v4 and self.ipv4_endpoint is None:
            subnets_v4 = [s for s in subnets if s.inet.version == 4]
            if len(subnets_v4) > 0:
                self.ipv4_endpoint = subnets_v4[0].inet.ip
                updated = True
        if v6 and self.ipv6_endpoint is None:
            subnets_v6 = [s for s in subnets if s.inet.version == 6]
            if len(subnets_v6) > 0:
                # With v6, we choose the second host of the subnet (cafe::1)
                gen = subnets_v6[0].inet.iter_hosts()
                gen.next()
                self.ipv6_endpoint = gen.next()
                updated = True
        return updated

    def check_endpoints(self, delete=False):
        """Check that the IP endpoints are included in one of the attributed IP
        subnets.

        If [delete] is True, then simply delete the faulty endpoints
        instead of raising an exception.
        """
        error = "L'IP {} n'est pas dans un réseau attribué."
        subnets = self.ip_subnet.all()
        is_faulty = lambda endpoint : endpoint and not any([endpoint in subnet.inet for subnet in subnets])
        if is_faulty(self.ipv4_endpoint):
            if delete:
                self.ipv4_endpoint = None
            else:
                raise ValidationError(error.format(self.ipv4_endpoint))
        if is_faulty(self.ipv6_endpoint):
            if delete:
                self.ipv6_endpoint = None
            else:
                raise ValidationError(error.format(self.ipv6_endpoint))

    def clean(self):
        # Generate VPN login, of the form "login-vpnX".  The resulting
        # login should not contain any ".", because graphite uses "." as a
        # separator.
        if not self.login:
            username = self.offersubscription.member.username
            vpns = VPNConfiguration.objects.filter(offersubscription__member__username=username)
            # This is the list of existing VPN logins for this user.
            logins = [vpn.login for vpn in vpns]
            # 100 VPNs ought to be enough for anybody.
            for login in ["{}-vpn{}".format(username, k) for k in range(1, 101)]:
                if login not in logins:
                    self.login = login
                    break
            # We may have failed.
            if not self.login:
                ValidationError("Impossible de générer un login VPN")
        # Hash password if needed
        self.password = utils.ldap_hash(self.password)
        # If saving for the first time and IP endpoints are not specified,
        # generate them automatically.
        if self.pk is None:
            self.generate_endpoints()
        self.check_endpoints()

    def __unicode__(self):
        return 'VPN ' + self.login

    class Meta:
        verbose_name = 'VPN'
        verbose_name_plural = 'VPN'


class LdapVPNConfig(ldapdb.models.Model):
    base_dn = settings.VPN_CONF_BASE_DN
    object_classes = ['person', 'organizationalPerson', 'inetOrgPerson',
                      'top', 'radiusprofile']

    login = CharField(db_column='cn', primary_key=True, max_length=255)
    sn = CharField(db_column='sn', max_length=255)
    password = CharField(db_column='userPassword', max_length=255)
    active = CharField(db_column='dialupAccess', max_length=3)
    ipv4_endpoint = CharField(db_column='radiusFramedIPAddress', max_length=16)
    ipv6_endpoint = CharField(db_column='postalAddress', max_length=40)
    ranges_v4 = ListField(db_column='radiusFramedRoute')
    ranges_v6 = ListField(db_column='registeredAddress')

    def __unicode__(self):
        return self.login

    class Meta:
        managed = False  # Indique à South de ne pas gérer le model LdapUser

vpn/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os
import urllib2

from django.http import StreamingHttpResponse, HttpResponseServerError
from django.shortcuts import get_object_or_404
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView
from django.conf import settings
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from coin.members.models import Member

from .models import VPNConfiguration


class VPNView(SuccessMessageMixin, UpdateView):
    model = VPNConfiguration
    fields = ['ipv4_endpoint', 'ipv6_endpoint', 'comment']
    success_message = "Configuration enregistrée avec succès !"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(VPNView, self).dispatch(*args, **kwargs)

    def get_form(self, form_class=None):
        if settings.MEMBER_CAN_EDIT_VPN_CONF:
            return super(VPNView, self).get_form(form_class)
        return None

    def get_object(self):
        if self.request.user.is_superuser:
            return get_object_or_404(VPNConfiguration, pk=self.kwargs.get("pk"))
        # For normal users, ensure the VPN belongs to them.
        return get_object_or_404(VPNConfiguration, pk=self.kwargs.get("pk"),
                                 offersubscription__member=self.request.user)


class VPNGeneratePasswordView(VPNView):
    """This generates a random password, saves it in hashed form, and returns
    it to the user in cleartext.
    """

    def get_context_data(self, **kwargs):
        context = super(VPNGeneratePasswordView, self).get_context_data(**kwargs)
        # Generate a new random password and save it
        password = Member.objects.make_random_password()
        self.object.password = password
        # This will hash the password automatically
        self.object.full_clean()
        self.object.save()
        context['password'] = password
        return context


@login_required
def get_graph(request, vpn_id, period="daily"):
    """ This get the graph for the associated vpn_id and time period
    """
    if request.user.is_superuser:
        vpn = get_object_or_404(VPNConfiguration, pk=vpn_id)
    else:
        # For normal users, ensure the VPN belongs to them
        vpn = get_object_or_404(VPNConfiguration, pk=vpn_id,
                                offersubscription__member=request.user)

    time_periods = { 'hourly': '-1hour', 'daily': '-24hours', 'weekly': '-8days', 'monthly': '-32days', 'yearly': '-13months', }
    if period not in time_periods:
        period = 'daily'

    graph_url = os.path.join(settings.GRAPHITE_SERVER,
                "render/?width=586&height=308&from=%(period)s&" \
                "target=alias%%28scaleToSeconds%%28vpn1.%(login)s.downrxbytes%%2C1%%29%%2C%%20%%22Download%%22%%29&" \
                "target=alias%%28scaleToSeconds%%28vpn1.%(login)s.uptxbytes%%2C1%%29%%2C%%20%%22Upload%%22%%29&" \
                "title=VPN%%20Usage%%20%(login)s" % \
                    { 'period': time_periods[period], 'login': vpn.login })
    try:
        return StreamingHttpResponse(urllib2.urlopen(graph_url), content_type="image/png")
    except urllib2.URLError:
        return HttpResponseServerError()

vpn/templates/vpn/vpn.html
{% extends "base.html" %}

{% load subnets %}
{% block title %}Configuration du VPN {{ object.offersubscription.get_subscription_reference }} - {{ block.super }}{% endblock %}
{% block content %}
<div class="row">
    <h2>Configuration du VPN</h2>
    {% if form %}
        <form class="flatform" action="{{ object.get_absolute_url }}" method="post">{% csrf_token %}
        <p class="legend">Quand vous aurez terminé vos modifications, cliquez sur <input class="button" type="submit" value="Valider" /></p>
    {% endif %}
    {% for message in messages %}
        <div class="message eat-up{% if message.tags %} {{ message.tags }}{% endif %}">
            {{ message }}
        </div>
    {% endfor %}

    {% if form %}
        {% if form.non_field_errors or form.ipv4_endpoint.errors or form.ipv6_endpoint.errors %}
            <div class="alert-box alert nogap">
            {{ form.non_field_errors }}
            {{ form.ipv4_endpoint.errors }}
            {{ form.ipv6_endpoint.errors }}
            </div>
        {% endif %}
    {% endif %}
    <div class="large-6 columns">
        <div class="panel">
            <h3>Authentification</h3>
            <table class="full-width">
                <tr>
                    <td class="center"><span class="label">Identifiant</span></td>
                    <td>{{object.login}}</td>
                </tr>
                {% if object.SECRETS_TRANSMISSION_METHOD == object.METHOD_GEN_PASSWORD_AND_FORGET %}
                <tr>
                    <td class="center" colspan="2">
                        <a class="button tiny radius" id="passgen" href="{% url 'vpn:generate_password' object.pk %}"><i class="fa fa-refresh"></i>
                            Générer un nouveau mot de passe</a>
                    </td>
                </tr>
                {% endif %}
                {% if object.SECRETS_TRANSMISSION_METHOD == object.METHOD_CRYPTO_LINK %}
                <tr>
                    <td class="center"><span class="label">Matériel cryptographique</span></td>
                    <td>
                        {% if object.crypto_link %}
                        <a href="{{object.crypto_link}}">Télecharger (lien supprimé après ouverture)</a>
                        {% else %}
                        Ton matériel cryptographique n'a pas encore été généré.
                        {% endif %}
                    </td>


                </tr>
                {% endif %}
                <tr class="flatfield">
                    {% if form %}
                        <td class="center">{{ form.comment.label_tag }}</td>
                        <td>{{ form.comment }}</td>
                    {% else %}
                    <td class="center"><span class="label">Commentaire</span></td>
                        <td>{{ object.comment }}</td>
                        
                    {% endif %}
                </tr>
                <tr>
                    <td class="center boolviewer" colspan="2">
                    {% if form %}
                        <input type="checkbox" disabled="disabled"{% if object.activated %} checked="checked"{% endif %} />
                    {% endif %}
                        <span>Ce VPN est {{ object.activated|yesno:"activé,désactivé" }}</span>
                    </td>
                </tr>
            </table>
        </div>
    </div>

    <div class="large-6 columns">
        <div class="panel">
            <h3>Adresses IP</h3>
            <table class="full-width">
                {% if form %}
                    <tr class="flatfield">
                        <td class="center">{{ form.ipv4_endpoint.label_tag }}</td>
                        <td{% if form.non_field_errors or form.ipv4_endpoint.errors %} class="errored"{% endif %}>{{ form.ipv4_endpoint }}</td>
                    </tr>
                    <tr class="flatfield">
                        <td class="center">{{ form.ipv6_endpoint.label_tag }}</td>
                        <td{% if form.non_field_errors or form.ipv6_endpoint.errors %} class="errored"{% endif %}>{{ form.ipv6_endpoint }}</td>
                    </tr>
                {% else %}
                    <tr class="flatfield">
                        <td class="center"><span class="label">IPv4</span></td>
                        <td>{{ object.ipv4_endpoint }}</td>
                    </tr>
                    <tr class="flatfield">
                        <td class="center"><span class="label">IPv6</span></td>
                        <td>{{ object.ipv6_endpoint }}</td>
                    </tr>
                {% endif %}
                <tr>
                    <td class="center"><span class="label">Sous-réseaux</span></td>
                    <td>
                        {% for subnet in object.ip_subnet.all %}{{ subnet|prettify }}<br/>{% endfor %}
                    </td>
                </tr>
            </table>
        </div>
    </div>
    {% if form %}
    <p class="formcontrol"><input class="button" type="submit" value="Valider" /></p>
    </form>
    {% endif %}
</div>

<div class="row" id="graph">
    <h3>Graphe de trafic sur
        <select id="graph_period">
            <option value="hourly">une heure</option>
            <option value="daily" selected>24 heures</option>
            <option value="weekly">7 jours</option>
            <option value="monthly">un mois</option>
            <option value="yearly">un an</option>
        </select> : <small class="pending_request"></small></h3>
    <img id="graph_trafic" src="{% url 'vpn:get_graph' vpn_id=object.pk %}" alt="Graphe de trafic {{ object.login }}" />
</div>

{% endblock %}

{% block extra_js %}
    <script>
        // Bouton génération du mot de passe
        $('#passgen').click(function(){
            if (!confirm("Ceci va effacer votre ancien mot de passe et en générer un nouveau. Continuer ?")) return false;

            parent_cell = $(this).parent();
            parent_cell.html('<span class="pending_request"><i class="fa fa-refresh fa-spin"></i> Génération en cours</span>');

            $.ajax({
                'url': $(this).attr('href')
            }).done(function(html) {
                //Remplace le tr parent par le contenu renvoyé (qui est deux tr successifs)
                parent_cell.parent().replaceWith(html);
            }).fail(function( jqXHR, textStatus ) {
                parent_cell.html('<span class="error">Échec de la requête : ' + textStatus + '</span>');
            });

            return false;
        });

        // Graphe de conso data
        $('#graph_period').change(function(){
            $('#graph .pending_request').html('<i class="fa fa-refresh fa-spin"></i>');
            base_url = "{% url 'vpn:get_graph' vpn_id=object.pk %}/";
            $('#graph_trafic').attr('src', base_url + $(this).val());
        });
        $('#graph_trafic').load(function() {
            $('#graph .pending_request').html('');
        });

    </script>
{% endblock extra_js %}