coin/billing/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url
from django.views.generic import DetailView
from coin.billing import views

urlpatterns = patterns(
    '',
    url(r'^invoice/(?P<id>.+)/pdf$', views.invoice_pdf, name="invoice_pdf"),
    url(r'^invoice/(?P<id>.+)$', views.invoice, name="invoice"),
    # url(r'^invoice/(?P<id>.+)/validate$', views.invoice_validate, name="invoice_validate"),
)

coin/members/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url
from coin.members import forms
from coin.members import views
from django.views.generic.base import TemplateView
from . import registration_views as views_r
from coin import settings

from registration.signals import user_activated
from django.contrib.auth import login

def login_on_activation(sender, user, request, **kwargs):
    """Logs in the user after activation"""
    user.backend = 'django.contrib.auth.backends.ModelBackend'
    login(request, user)

# Registers the function with the django-registration user_activated signal
user_activated.connect(login_on_activation)

urlpatterns = patterns(
    '',
    url(r'^$', views.index, name='index'),
    url(r'^login/$', 'django.contrib.auth.views.login',
        {'template_name': 'members/registration/login.html',
         'extra_context': {'settings': settings} },
        name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login',
        name='logout'),

    url(r'^password_change/$', 'django.contrib.auth.views.password_change',
        {'post_change_redirect': 'members:password_change_done',
         'template_name': 'members/registration/password_change_form.html'},
        name='password_change'),
    url(r'^password_change_done/$', 'django.contrib.auth.views.password_change_done',
        {'template_name': 'members/registration/password_change_done.html'},
        name='password_change_done'),

    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset',
        {'post_reset_redirect': 'members:password_reset_done',
         'template_name': 'members/registration/password_reset_form.html',
         'email_template_name': 'members/registration/password_reset_email.html',
         'subject_template_name': 'members/registration/password_reset_subject.txt'},
        name='password_reset'),
    url(r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done',
        {'template_name': 'members/registration/password_reset_done.html',
         'current_app': 'members'},
        name='password_reset_done'),
    url(r'^password_reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm',
        {'post_reset_redirect': 'members:password_reset_complete',
         'template_name': 'members/registration/password_reset_confirm.html'},
        name='password_reset_confirm'),
    url(r'^password_reset/complete/$', 'django.contrib.auth.views.password_reset_complete',
        {'template_name': 'members/registration/password_reset_complete.html'},
        name='password_reset_complete'),


    url(r'^activate/complete/$', views.activation_completed,
        name='registration_activation_complete'),
    # The activation key can make use of any character from the
    # URL-safe base64 alphabet, plus the colon as a separator.
    url(r'^activate/(?P<activation_key>[-:\w]+)/$',
        views_r.MemberActivationView.as_view(),
        name='registration_activate'),
    url(r'^register/$',
        views_r.MemberRegistrationView.as_view(
            form_class=forms.MemberRegistrationForm,
            template_name='members/registration/registration_form.html'
        ),
        name='registration_register'),
    url(r'^register/complete/$',
        TemplateView.as_view(
            template_name='members/registration/registration_complete.html'
        ),
        name='registration_complete'),
    url(r'^register/closed/$',
        TemplateView.as_view(
            template_name='members/registration/registration_closed.html'
        ),
        name='registration_disallowed'),
    #url(r'', include('registration.auth_urls')),




    url(r'^detail/$', views.detail,
        name='detail'),

    url(r'^subscriptions/', views.subscriptions, name='subscriptions'),
    # url(r'^subscription/(?P<id>\d+)', views.subscriptions, name = 'subscription'),

    url(r'^invoices/', views.invoices, name='invoices'),
    url(r'^contact/', views.contact, name='contact'),
)

coin/offers/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url
from coin.offers.views import ConfigurationRedirectView, subscription_count_json

urlpatterns = patterns(
    '',
    # Redirect to the appropriate configuration backend.
    url(r'^configuration/(?P<id>.+)$', ConfigurationRedirectView.as_view(), name="configuration-redirect"),
    url(r'^api/v1/count$', subscription_count_json),
)

coin/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.apps import apps
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from coin import views
import coin.apps

import autocomplete_light
autocomplete_light.autodiscover()

from django.contrib import admin
admin.autodiscover()

from coin.isp_database.views import isp_json


def apps_urlpatterns():
    """ Yields url lists ready to be appended to urlpatterns list
    """
    for app_config in apps.get_app_configs():
        if isinstance(app_config, coin.apps.AppURLs):
            for prefix, pats in app_config.exported_urlpatterns:
                yield url(
                    r'^{}/'.format(prefix),
                    include(pats, namespace=prefix))

urlpatterns = patterns(
    '',
    url(r'^$', 'coin.members.views.index', name='home'),

    url(r'^isp.json$', isp_json),
    url(r'^members/', include('coin.members.urls', namespace='members')),
    url(r'^billing/', include('coin.billing.urls', namespace='billing')),
    url(r'^subscription/', include('coin.offers.urls', namespace='subscription')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^hijack/', include('hijack.urls', namespace='hijack')),

    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^feed/(?P<feed_name>.+)', views.feed, name='feed'),

    url(r'^autocomplete/', include('autocomplete_light.urls')),

)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Pluggable apps URLs
urlpatterns += list(apps_urlpatterns())


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

vpn/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from .views import VPNView, VPNGeneratePasswordView, get_graph

urlpatterns = patterns(
    '',
    # This is part of the generic configuration interface (the "name" is
    # the same as the "backend_name" of the model).
    url(r'^(?P<pk>\d+)$', VPNView.as_view(template_name="vpn/vpn.html"), name="details"),
    url(r'^password/(?P<pk>\d+)$', VPNGeneratePasswordView.as_view(template_name="vpn/fragments/password.html"), name="generate_password"),
    url(r'^graph/(?P<vpn_id>[0-9]+)/(?P<period>[a-z]+)$', get_graph, name="get_graph"),
    url(r'^graph/(?P<vpn_id>[0-9]+)$', get_graph, name="get_graph"),
)

coin/billing/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os

from django.core.exceptions import ValidationError
from django import forms

def validate_file_extension(value):
    ext = os.path.splitext(value.name)[1]
    valid_extensions = ['.csv']
    if not ext.lower() in valid_extensions:
        raise ValidationError(u'Unsupported file extension.')

class WizardImportPaymentCSV(forms.Form):

    csv_file = forms.FileField(validators=[validate_file_extension])

coin/configuration/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.forms import ModelForm, ValidationError
from django.db.models import Q
from django import forms

from coin.offers.models import OfferSubscription
from coin.configuration.models import Configuration


class ConfigurationForm(ModelForm):
    class Meta:
        model = Configuration
        widgets = {
            'comment': forms.Textarea(),
        }
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        """
        This filter the offersubscription select field in configurations forms
        to only display subscription that are the sames type of actual configuration
        and that haven't already a configuration associated with
        """
        super(ConfigurationForm, self).__init__(*args, **kwargs)
        if self.instance:
            queryset = OfferSubscription.objects.filter(
                Q(offer__configuration_type=self.instance.model_name) & (
                Q(configuration=None) | Q(configuration=self.instance.pk)))
            self.fields['offersubscription'].queryset = queryset

    def clean_offersubscription(self):
        """
        This check if the selected administrative subscription is linked to an
        offer which use the same configuration type than the edited configuration.
        """
        offersubscription = self.cleaned_data['offersubscription']
        if offersubscription.offer.configuration_type != self.instance.model_name():
            raise ValidationError('Administrative subscription must refer an offer having a "{}" configuration type.'.format(self.instance.model_name()))

        return offersubscription

coin/billing/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render
from django.contrib import messages

from sendfile import sendfile

from coin.billing.models import Invoice
from coin.members.models import Member
from coin.html2pdf import render_as_pdf
from coin.billing.utils import get_invoice_from_id_or_number, assert_user_can_view_the_invoice


def invoice_pdf(request, id):
    """
    Renvoi une facture générée en format pdf
    id peut être soit la pk d'une facture, soit le numero de facture
    """
    invoice = get_invoice_from_id_or_number(id)

    assert_user_can_view_the_invoice(request, invoice)

    pdf_filename = 'Facture_%s.pdf' % invoice.number

    return sendfile(request, invoice.pdf.path,
                    attachment=True, attachment_filename=pdf_filename)


def invoice(request, id):
    """
    Affiche une facture et son détail
    id peut être soit la pk d'une facture, soit le numero de facture
    """
    invoice = get_invoice_from_id_or_number(id)

    assert_user_can_view_the_invoice(request, invoice)

    return render(request, 'billing/invoice.html', {"invoice": invoice})

    return response

coin/configuration/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

coin/isp_database/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json

from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.views.decorators.cache import cache_control

from coin.isp_database.models import ISPInfo


@cache_control(max_age=7200)
def isp_json(request):
    try:
        isp = ISPInfo.objects.get()
    except ISPInfo.DoesNotExist:
        raise Http404
    data = isp.to_dict()
    return HttpResponse(json.dumps(data), content_type="application/json")

coin/members/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.template import RequestContext
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.conf import settings
from forms import PersonMemberChangeForm, OrganizationMemberChangeForm

@login_required
def index(request):
    has_isp_feed = 'isp' in [k for k, _, _ in settings.FEEDS]
    return render(request, 'members/index.html',
                  {'has_isp_feed': has_isp_feed})


@login_required
def detail(request):

    membership_info_url = settings.MEMBER_MEMBERSHIP_INFO_URL
    context={
        'membership_info_url': membership_info_url,
    }

    if settings.MEMBER_CAN_EDIT_PROFILE:
        if request.user.type == "natural_person":
            form_cls = PersonMemberChangeForm
        else:
            form_cls = OrganizationMemberChangeForm

        if request.method == "POST":
            form = form_cls(data = request.POST, instance = request.user)
            if form.is_valid():
                form.save()
        else:
            form = form_cls(instance = request.user)

        context['form'] = form

    return render(request, 'members/detail.html', context)


@login_required
def subscriptions(request):
    subscriptions = request.user.get_active_subscriptions()
    old_subscriptions = request.user.get_inactive_subscriptions()

    return render(request, 'members/subscriptions.html',
                  {'subscriptions': subscriptions,
                   'old_subscriptions': old_subscriptions})


@login_required
def invoices(request):
    balance  = request.user.balance
    invoices = request.user.invoices.filter(validated=True).order_by('-date')
    payments = request.user.payments.filter().order_by('-date')

    return render(request, 'members/invoices.html',
                              {'balance' : balance,
                               'handle_balance' : settings.HANDLE_BALANCE,
                               'invoices': invoices,
                               'payments': payments})


@login_required
def contact(request):
    return render(request, 'members/contact.html')


@login_required
def activation_completed(request):
    label_template = settings.MEMBERSHIP_REFERENCE.format(user=request.user)
    context = {
        'bank_transfer_label': label_template,
        'dues': settings.DEFAULT_MEMBERSHIP_FEE
    }

    return render(request, 'members/registration/activation_complete.html',
                  context)

coin/offers/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime
import json

from django.db.models import Q, Count
from django.views.generic.base import RedirectView
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse
from django.http import JsonResponse, HttpResponseServerError
# from django.views.decorators.cache import cache_control

from coin.offers.models import Offer, OfferSubscription

class ConfigurationRedirectView(RedirectView):
    """Redirects to the appropriate view for the configuration backend of the
    specified subscription."""

    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        subscription = get_object_or_404(OfferSubscription, pk=self.kwargs['id'],
                                         member=self.request.user)
        return reverse(subscription.configuration.url_namespace + ':' + subscription.configuration.backend_name,
                       args=[subscription.configuration.pk])


# @cache_control(max_age=7200)
def subscription_count_json(request):
    output = []

    # Get date form url, or set default
    date = request.GET.get('date', datetime.date.today())

    # Validate date type
    if not isinstance(date, datetime.date):
        try:
            datetime.datetime.strptime(date, '%Y-%m-%d')
        except ValueError, TypeError:
            return HttpResponseServerError("Incorrect date format, should be YYYY-MM-DD")

    # Get current offer subscription
    offersubscriptions = list(OfferSubscription.objects.running(date).offer_summary())
    for offersub in offersubscriptions:
        output.append({
            'reference' : offersub['offer__reference'],
            'name' : offersub['offer__name'],
            'subscriptions_count' : offersub['num_subscriptions']
        })

    # Return JSON
    return JsonResponse(output, safe=False)

coin/resources/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

coin/reverse_dns/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

coin/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import feedparser
import HTMLParser

from django.views.decorators.cache import cache_page
from django.template import RequestContext
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseServerError
from django.conf import settings


@cache_page(60 * 60 * 24) # Cache 24h
def feed(request, feed_name):
    feeds = settings.FEEDS
    feed = None
    # Recherce le flux passé en paramètre dans les flux définis dans settings
    for feed_search in feeds:
        if (feed_search[0] == feed_name):
            feed = feed_search
            break

    # Si le flux n'a pas été trouvé ou qu'il n'y a pas d'URL donnée, renvoi 404
    if not feed or len(feed)<2 or not feed[1]:
        return HttpResponseNotFound('')
    # Sinon récupère les informations (url et limit)
    else:
        feed_url = feed[1]
        if len(feed) >=3:
            limit = feed[2]
        else:
            limit = 3

    try:
        feed = feedparser.parse(feed_url)
        entries = feed.entries[:limit]

        return render(request, 'fragments/feed.html',
                                  {'feed_entries': entries})
    except:
        return HttpResponseServerError('')

coin/templates/base.html
<!doctype html>
{% load staticfiles %}
{% load hijack_tags %}
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{{ SITE_TITLE }}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "css/foundation.css"%}" />
    <link rel="stylesheet" href="{% static "css/font-awesome.min.css"%}" />
    <link rel="stylesheet" href="{% static "css/local.css" %}" />
    <link rel="stylesheet" href="{% static "css/offcanvas.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static 'hijack/hijack-styles.css' %}" />
    {% block extra_css %}{% endblock %}
    <script src="{% static "js/vendor/modernizr.js" %}"></script>
    <link rel="icon" type="image/png" href="{% static "img/coinitem.png" %}"/>
    <link rel="icon" type="image/x-icon" href="{% static "img/favicon.ico" %}" />
</head>
<body>
{% hijack_notification %}
<div class="off-canvas-wrap" data-offcanvas>
    <div class="inner-wrap">

        {% if user.is_authenticated %}
        <aside class="left-off-canvas-menu">
            <ul class="off-canvas-list">
                <li><label>Menu</label></li>
                {% include "menu_items.html" %}
            </ul>
        </aside>
        {% endif %}

        <header>
            <div class="show-for-medium-up">
                <div class="row">
                    <div class="large-12">
                        <h1>
                            {% if SITE_LOGO_URL %}
                            <span class="medium-3 large-3 columns">
                                <img src="{{ SITE_LOGO_URL }}" alt="" />
                            </span
                            {% else %}
                            <span class="default-logo">&nbsp;</span>
                            {% endif %}
                            <a href="{% url 'home' %}">{{ SITE_HEADER }}</a>
                        </h1>
                    </div>
                </div>
            </div>
            <div class="show-for-small">
                <nav class="tab-bar">
                    {% if user.is_authenticated %}
                    <section class="left-small">
                        <a class="left-off-canvas-toggle menu-icon" href="#"><span></span></a>
                    </section>
                    {% endif %}

                    <section class="middle tab-bar-section">
                        <h1 class="title">COIN</h1>
                    </section>

                </nav>
            </div>
        </header>


        <div class="row">
            {% if user.is_authenticated %}
            <div class="medium-3 large-3 columns">
                {% block sidenav %}
                <nav id="sidebox" class="show-for-medium-up">
                    <ul class="side-nav">
                        {% include "menu_items.html" %}
                    </ul>
                </nav>
                {% endblock %}
            </div>
            {% endif %}

            <div class="medium-{% if user.is_authenticated %}9{% else %}12{% endif %} large-{% if user.is_authenticated %}9{% else %}12{% endif %} columns">
                {% block content %}{% endblock %}
            </div>
        </div>

        
        <div id="footer">
            {% block footer %}
            <div class="row">
                <div class="small-5 columns"><div class="line">&nbsp;</div></div>
                <div class="small-2 columns"><div class="duck"></div></div>
                <div class="small-5 columns"><div class="line">&nbsp;</div></div>
            </div>
            <p class="licence-sentence">Site propulsé par <a href="https://code.ffdn.org/FFDN/coin">COIN</a> sous licence AGPLv3.</p>
            {% endblock %}
        </div>

        <a class="exit-off-canvas"></a>
    </div> <!-- .inner-wrap -->
</div> <!-- .off-canvas-wrap -->


<script src="{% static "js/vendor/jquery.js" %}"></script>
<script src="{% static "js/foundation.min.js" %}"></script>
<script src="{% static "js/foundation/foundation.offcanvas.js" %}"></script>
<script src="{% static "js/utils.js" %}"></script>
{% block extra_js %}{% endblock extra_js %}

<script>
  $(document).foundation();
</script>

</body>
</html>

coin/templates/menu_items.html
{% load activelink %}
<li class="{% ifactive 'home' %}active{% endifactive %}"><a href="{% url 'home' %}"><i class="fa fa-home fa-fw"></i> Tableau de bord</a></li>
<li class="{% ifactive 'members:detail' %}active{% endifactive %}"><a href="{% url 'members:detail' %}"><i class="fa fa-user fa-fw"></i> Mes informations</a></li>
<li class="{% ifactive 'members:subscriptions' %}active{% endifactive %}"><a href="{% url 'members:subscriptions' %}"><i class="fa fa-cog fa-fw"></i> Mes abonnements</a></li>
<li class="{% ifactive 'members:invoices' %}active{% endifactive %}"><a href="{% url 'members:invoices' %}"><i class="fa fa-eur fa-fw"></i> Factures &amp; paiements</a></li>
{% if 'hardware_provisioning' in INSTALLED_APPS %}
<li class="{% ifactive 'hardware_provisioning:loan-list' %}active{% endifactive %}"><a href="{% url 'hardware_provisioning:loan-list' %}"><i
            class="fa fa-exchange fa-fw"></i> Mon matériel</a></li>
{% endif %}
{% if 'maillists' in INSTALLED_APPS %}
<li class="{% ifactive 'maillists:lists-list' %}active{% endifactive %}"><a href="{% url 'maillists:lists-list' %}"><i
            class="fa fa-envelope fa-fw"></i> Listes mail</a></li>

{% endif %}
<li class="{% ifactive 'members:contact' %}active{% endifactive %}"><a href="{% url 'members:contact' %}"><i class="fa fa-life-ring fa-fw"></i> Contact / Support</a></li>
<li class="divider"></li>
{% if user.is_staff %}<li><a href="{% url 'admin:index' %}"><i class="fa fa-cogs fa-fw"></i> Administration</a></li>{% endif %}
<li class="{% ifactive 'members:password_change' %}active{% endifactive %}"><a href="{% url 'members:password_change' %}"><i class="fa fa-key fa-fw"></i> Modifier mon mot de passe</a></li>
<li class="divider"></li>
<li class="{% ifactive '' %}active{% endifactive %}"><a href="{% url 'members:logout' %}"><i class="fa fa-power-off fa-fw"></i> Déconnexion</a></li>